import type { IconType } from "react-icons";
import {
  SiReact,
  SiElectron,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiSass,
  SiTailwindcss,
  SiChakraui,
  SiRedux,
  SiReactquery,
  SiNodedotjs,
  SiPython,
  SiFlask,
  SiDjango,
  SiMysql,
  SiGit,
  SiGithub,
  SiPostman,
  SiSelenium,
  SiVitest,
  SiJira,
  SiScrumalliance,
  SiGithubactions,
} from "react-icons/si";

/**
 * Maps a skill label (as it appears in messages/*.json) to its brand icon.
 * Labels with no entry here are not rendered in the skills section (icons only).
 * Processes with no logo are represented by the icon of a representative tool (e.g. Scrum -> Scrum Alliance).
 */
export const techIcons: Record<string, IconType> = {
  "React.js": SiReact,
  "React Native": SiReact,
  "Electron.js": SiElectron,
  TypeScript: SiTypescript,
  "JavaScript (ES6+)": SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss,
  SASS: SiSass,
  "Tailwind CSS": SiTailwindcss,
  "Chakra UI": SiChakraui,
  Redux: SiRedux,
  "TanStack Query": SiReactquery,
  "Node.js": SiNodedotjs,
  Python: SiPython,
  Flask: SiFlask,
  Django: SiDjango,
  MySQL: SiMysql,
  Git: SiGit,
  GitHub: SiGithub,
  "APIs REST": SiPostman,
  "REST APIs": SiPostman,
  "Pruebas funcionales": SiSelenium,
  "Functional testing": SiSelenium,
  "Pruebas unitarias": SiVitest,
  "Unit testing": SiVitest,
  "Documentación de bugs": SiJira,
  "Bug documentation": SiJira,
  Scrum: SiScrumalliance,
  "CI/CD": SiGithubactions,
};
